In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import random

In [3]:
X,y = make_classification(n_features=5, n_redundant=0, n_informative=5,n_clusters_per_class=1)

In [4]:
df = pd.DataFrame(X,columns=['col1','col2','col3','col4','col5'])
df['target'] = y
print(df.shape)
df.head()

(100, 6)


col1      col2      col3      col4      col5  target
0 -0.068526 -2.516208  1.397183 -0.265108 -0.563340       1
1 -0.403093 -3.018734  0.655504  0.567058 -0.818990       1
2 -0.120389 -0.441885 -0.001060 -1.103803 -0.459072       1
3 -1.817612 -1.630395  0.236103  0.620253  2.838767       0
4  2.129671 -0.225057  0.537678 -2.156390 -1.145793       1

In [8]:
def sample_rows(df,percent):
  return df.sample(int(percent*df.shape[0]),replace=True)

def sample_features(df,percent):
  cols = random.sample(df.columns.tolist()[:-1],int(percent*(df.shape[1]-1)))
  new_df = df[cols]
  new_df['target'] = df['target']
  return new_df

def combined_sampling(df,row_percent,col_percent):
  new_df = sample_rows(df,row_percent)
  return sample_features(new_df,col_percent)

In [9]:
df1 = combined_sampling(df,0.5,0.5)
df2 = combined_sampling(df,0.5,0.5)
df3 = combined_sampling(df,0.5,0.5)

C:\Users\rohan\AppData\Local\Temp\ipykernel_19676\2993133343.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']
C:\Users\rohan\AppData\Local\Temp\ipykernel_19676\2993133343.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']
C:\Users\rohan\AppData\Local\Temp\ipykernel_19676\2993133343.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See th

In [10]:
from sklearn.tree import DecisionTreeClassifier
clf1 = DecisionTreeClassifier()
clf2 = DecisionTreeClassifier()
clf3 = DecisionTreeClassifier()

In [11]:
clf1.fit(df1.iloc[:,0:2],df1.iloc[:,-1])
clf2.fit(df2.iloc[:,0:2],df2.iloc[:,-1])
clf3.fit(df3.iloc[:,0:2],df3.iloc[:,-1])

DecisionTreeClassifier()

In [12]:
clf1.predict(np.array([-1.042498,	-0.064323]).reshape(1,2))

c:\Users\rohan\anaconda3\envs\DL\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [13]:
clf2.predict(np.array([-1.042498,	-0.064323]).reshape(1,2))

c:\Users\rohan\anaconda3\envs\DL\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [14]:
clf3.predict(np.array([-1.042498,	-0.064323]).reshape(1,2))

c:\Users\rohan\anaconda3\envs\DL\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])