In [12]:
import pandas as pd
import numpy as np

In [13]:
np.random.seed(23)
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0], [0,1,0], [0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

In [14]:
df = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target'] = 1

In [15]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0], [0,1,0], [0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

In [16]:
df1 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target'] = 0

In [17]:
df = pd.concat([df, df1])
df = df.sample(40)

In [19]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
14  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [21]:
!pip3 install plotly

     ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
     - -------------------------------------- 0.5/15.5 MB 11.3 MB/s eta 0:00:02
     --- ------------------------------------ 1.5/15.5 MB 15.8 MB/s eta 0:00:01
     ----- ---------------------------------- 2.2/15.5 MB 15.8 MB/s eta 0:00:01
     -------- ------------------------------- 3.2/15.5 MB 16.7 MB/s eta 0:00:01
     ---------- ----------------------------- 4.1/15.5 MB 17.2 MB/s eta 0:00:01
     ------------ --------------------------- 5.0/15.5 MB 17.8 MB/s eta 0:00:01
     --------------- ------------------------ 5.9/15.5 MB 18.0 MB/s eta 0:00:01
     ----------------- ---------------------- 6.8/15.5 MB 18.0 MB/s eta 0:00:01
     ------------------- -------------------- 7.6/15.5 MB 17.9 MB/s eta 0:00:01
     --------------------- ------------------ 8.4/15.5 MB 17.9 MB/s eta 0:00:01
     ----------------------- ---------------- 9.3/15.5 MB 17.9 MB/s eta 0:00:01
     ------------------------- ------------- 10.

In [22]:
import plotly.express as px
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'], color=df['target'].astype('str'))
fig.update_traces(marker = dict(size=12, line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig.show()

In [23]:
#Apply scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:, 0:3] = scaler.fit_transform(df.iloc[:, 0:3])

In [24]:
# find covariance matrix
covariance_matrix = np.cov([df.iloc[:, 0], df.iloc[:,1], df.iloc[:, 2]])
print(covariance_matrix)

[[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [25]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [27]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [28]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [31]:
pc = eigen_vectors[:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [41]:
transformed_df = np.dot(df.iloc[:, 0:3], pc.T)
transformed_df[:5]

array([[ 0.59943321,  1.79586208],
       [ 1.05691919, -0.2127375 ],
       [-0.27187555,  0.49822203],
       [-0.62158585,  0.02311035],
       [ 1.56728555,  1.73096695]])

In [37]:
new_df = pd.DataFrame(transformed_df, columns=['PC1', 'PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [38]:
fig2 = px.scatter(df, x=df['feature1'], y=df['feature2'], color=df['target'].astype('str'))
fig2.update_traces(marker = dict(size=12, line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig2.show()